import { createPortal } from 'react-dom';
import type { RecommendationItem } from '../types';
import { downloadReportPdf } from '../utils/reportPdf';

export type AnalysisReportContext = {
  title: string;
  targetRole?: string;
  analyzedAt?: string;
  summary?: string;
  scores?: Record<string, string | number>;
};

type JustificationReportModalProps = {
  open: boolean;
  context: AnalysisReportContext;
  items: RecommendationItem[];
  focusIndex?: number | null;
  onClose: () => void;
};

function formatPriority(priority?: string) {
  return (priority || 'medium').toUpperCase();
}

function hasJustification(item: RecommendationItem) {
  return Boolean(item.justification?.trim() && item.evidence?.trim());
}

export function buildReportText(
  context: AnalysisReportContext,
  items: RecommendationItem[],
  focusIndex?: number | null,
): string {
  const lines: string[] = [
    context.title,
    '='.repeat(context.title.length),
    '',
  ];

  if (context.targetRole) lines.push(`Target role: ${context.targetRole}`);
  if (context.analyzedAt) {
    lines.push(`Analyzed: ${new Date(context.analyzedAt).toLocaleString()}`);
  }
  if (context.summary) {
    lines.push('');
    lines.push('Summary');
    lines.push(context.summary);
  }
  if (context.scores && Object.keys(context.scores).length > 0) {
    lines.push('');
    lines.push('Scores');
    for (const [key, value] of Object.entries(context.scores)) {
      lines.push(`- ${key}: ${value}`);
    }
  }

  const reportItems =
    focusIndex != null && focusIndex >= 0 && focusIndex < items.length
      ? [items[focusIndex]]
      : items;

  lines.push('');
  lines.push(focusIndex != null ? 'Recommendation detail' : 'Recommendations');
  lines.push('-'.repeat(40));

  reportItems.forEach((item, index) => {
    const num = focusIndex != null ? focusIndex + 1 : index + 1;
    lines.push('');
    lines.push(`${num}. ${item.text}`);
    lines.push(`   Priority: ${formatPriority(item.priority)}`);
    if (item.justification?.trim()) {
      lines.push(`   Why: ${item.justification}`);
    }
    if (item.evidence?.trim()) {
      lines.push(`   Evidence: ${item.evidence}`);
    }
  });

  lines.push('');
  lines.push(`Generated by CareerSucceX — ${new Date().toLocaleString()}`);
  return lines.join('\n');
}

export default function JustificationReportModal({
  open,
  context,
  items,
  focusIndex = null,
  onClose,
}: JustificationReportModalProps) {
  if (!open) return null;

  const displayItems = items;
  const missingJustifications = displayItems.some((item) => !hasJustification(item));

  const focused =
    focusIndex != null && focusIndex >= 0 && focusIndex < displayItems.length
      ? displayItems[focusIndex]
      : null;

  const reportItems = focused ? [focused] : displayItems;
  const modalTitle = focused ? 'Recommendation detail' : 'Full analyzed report';

  const handleDownload = () => {
    downloadReportPdf(context, displayItems, focusIndex);
  };

  return createPortal(
    <div
      className="report-modal-overlay"
      role="dialog"
      aria-modal="true"
      aria-labelledby="report-modal-title"
      onClick={onClose}
    >
      <div className="report-modal" onClick={(e) => e.stopPropagation()}>
        <div className="report-modal__header">
          <div>
            <p className="report-modal__eyebrow">{context.title}</p>
            <h2 id="report-modal-title" className="report-modal__title">
              {modalTitle}
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="report-modal__close"
            aria-label="Close report"
          >
            ×
          </button>
        </div>

        <div className="report-modal__meta">
          {context.targetRole && (
            <span>
              Role: <strong>{context.targetRole}</strong>
            </span>
          )}
          {context.analyzedAt && (
            <span>{new Date(context.analyzedAt).toLocaleString()}</span>
          )}
        </div>

        <div className="report-modal__body">
          {context.summary && (
            <section className="report-modal__section">
              <h3 className="report-modal__section-title">Summary</h3>
              <p className="report-modal__text report-modal__text--summary">{context.summary}</p>
            </section>
          )}

          {context.scores && Object.keys(context.scores).length > 0 && (
            <section className="report-modal__section">
              <h3 className="report-modal__section-title">Scores</h3>
              <dl className="report-modal__scores">
                {Object.entries(context.scores).map(([label, value]) => (
                  <div key={label} className="report-modal__score-row">
                    <dt>{label}</dt>
                    <dd>{value}</dd>
                  </div>
                ))}
              </dl>
            </section>
          )}

          <section className="report-modal__section">
            <h3 className="report-modal__section-title">
              {focused ? 'Recommendation' : `Detailed recommendations (${displayItems.length})`}
            </h3>
            {missingJustifications && (
              <p className="report-modal__text report-modal__text--muted">
                Re-run analysis to generate AI-specific justifications grounded in your CV or GitHub data.
              </p>
            )}
            <div className="report-modal__items">
              {reportItems.map((item, i) => {
                const displayIndex = focused ? (focusIndex ?? 0) + 1 : i + 1;
                return (
                  <article key={`${item.text}-${displayIndex}`} className="report-modal__item">
                    <div className="report-modal__item-head">
                      <span className="report-modal__item-index">{displayIndex}</span>
                      <p className="report-modal__item-text">{item.text}</p>
                      <span className="report-modal__priority">{formatPriority(item.priority)}</span>
                    </div>
                    {item.justification?.trim() ? (
                      <div className="report-modal__detail">
                        <span className="report-modal__detail-label">Why this matters</span>
                        <p>{item.justification}</p>
                      </div>
                    ) : null}
                    {item.evidence?.trim() ? (
                      <div className="report-modal__detail">
                        <span className="report-modal__detail-label">Evidence</span>
                        <p>{item.evidence}</p>
                      </div>
                    ) : null}
                  </article>
                );
              })}
            </div>
          </section>
        </div>

        <div className="report-modal__actions">
          <button type="button" onClick={onClose} className="analytics-btn-ghost px-4 py-2 text-sm">
            Close
          </button>
          <button type="button" onClick={handleDownload} className="btn-aurora px-4 py-2 text-sm">
            Download PDF
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}
