import { jsPDF } from 'jspdf';
import type { AnalysisReportContext } from '../components/JustificationReportModal';
import type { RecommendationItem } from '../types';

const MARGIN = 18;
const PAGE_HEIGHT = 297;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = PAGE_HEIGHT - 12;

function formatPriority(priority?: string) {
  return (priority || 'medium').toUpperCase();
}

function reportItems(
  items: RecommendationItem[],
  focusIndex?: number | null,
): RecommendationItem[] {
  if (focusIndex != null && focusIndex >= 0 && focusIndex < items.length) {
    return [items[focusIndex]];
  }
  return items;
}

export function buildReportPdfFilename(
  context: AnalysisReportContext,
  focusIndex?: number | null,
): string {
  const slug = context.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const suffix =
    focusIndex != null && focusIndex >= 0 ? `-item-${focusIndex + 1}` : '-full';
  return `${slug || 'analysis-report'}${suffix}.pdf`;
}

export function downloadReportPdf(
  context: AnalysisReportContext,
  items: RecommendationItem[],
  focusIndex?: number | null,
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = MARGIN;

  const addPageIfNeeded = (height: number) => {
    if (y + height > FOOTER_Y - 4) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const lineHeight = (fontSize: number) => fontSize * 0.42;

  const writeLines = (
    lines: string[],
    fontSize: number,
    style: 'normal' | 'bold' | 'italic' = 'normal',
    x = MARGIN,
    color: [number, number, number] = [35, 35, 35],
  ) => {
    if (!lines.length) return;
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    const height = lines.length * lineHeight(fontSize) + 1.5;
    addPageIfNeeded(height);
    doc.text(lines, x, y);
    y += height;
  };

  const writeWrapped = (
    text: string,
    fontSize: number,
    style: 'normal' | 'bold' | 'italic' = 'normal',
    x = MARGIN,
    maxWidth = CONTENT_WIDTH,
    color: [number, number, number] = [35, 35, 35],
  ) => {
    const lines = doc.splitTextToSize(text, maxWidth) as string[];
    writeLines(lines, fontSize, style, x, color);
  };

  const sectionTitle = (title: string) => {
    addPageIfNeeded(14);
    y += 5;
    writeLines([title.toUpperCase()], 11, 'bold', MARGIN, [32, 96, 88]);
    doc.setDrawColor(210, 225, 222);
    doc.line(MARGIN, y - 2, PAGE_WIDTH - MARGIN, y - 2);
    y += 2;
  };

  writeLines([context.title], 18, 'bold', MARGIN, [18, 74, 66]);
  y += 1;

  if (context.targetRole) {
    writeWrapped(`Target role: ${context.targetRole}`, 10, 'normal', MARGIN, CONTENT_WIDTH, [70, 70, 70]);
  }
  if (context.analyzedAt) {
    writeWrapped(
      `Analyzed: ${new Date(context.analyzedAt).toLocaleString()}`,
      10,
      'normal',
      MARGIN,
      CONTENT_WIDTH,
      [70, 70, 70],
    );
  }

  if (context.summary?.trim()) {
    sectionTitle('Summary');
    writeWrapped(context.summary.trim(), 11);
  }

  if (context.scores && Object.keys(context.scores).length > 0) {
    sectionTitle('Scores');
    for (const [label, value] of Object.entries(context.scores)) {
      addPageIfNeeded(8);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(70, 70, 70);
      doc.text(label, MARGIN, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(35, 35, 35);
      doc.text(String(value), MARGIN + 52, y);
      y += 6.5;
    }
    y += 1;
  }

  const selectedItems = reportItems(items, focusIndex);
  const focused = focusIndex != null && focusIndex >= 0 && focusIndex < items.length;
  sectionTitle(
    focused ? 'Recommendation' : `Detailed recommendations (${selectedItems.length})`,
  );

  selectedItems.forEach((item, index) => {
    const displayIndex = focused ? (focusIndex ?? 0) + 1 : index + 1;
    addPageIfNeeded(18);
    y += 2;
    writeWrapped(`${displayIndex}. ${item.text}`, 10, 'bold');
    writeWrapped(`Priority: ${formatPriority(item.priority)}`, 9, 'normal', MARGIN + 2, CONTENT_WIDTH - 2, [90, 90, 90]);

    if (item.justification?.trim()) {
      writeWrapped('Why this matters', 9, 'bold', MARGIN + 2, CONTENT_WIDTH - 2, [32, 96, 88]);
      writeWrapped(item.justification.trim(), 10, 'normal', MARGIN + 2, CONTENT_WIDTH - 2);
    }
    if (item.evidence?.trim()) {
      writeWrapped('Evidence', 9, 'bold', MARGIN + 2, CONTENT_WIDTH - 2, [32, 96, 88]);
      writeWrapped(item.evidence.trim(), 10, 'normal', MARGIN + 2, CONTENT_WIDTH - 2);
    }
    y += 2;
  });

  addPageIfNeeded(8);
  writeWrapped(
    `Generated by CareerSucceX — ${new Date().toLocaleString()}`,
    8,
    'italic',
    MARGIN,
    CONTENT_WIDTH,
    [130, 130, 130],
  );

  doc.save(buildReportPdfFilename(context, focusIndex));
}
